package com.vcredit.vmc.rules.drools.input;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AndiCheckInput implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AndiCheckInput() {
    }




}