package com.vcredit.vmc.rules.drools.output;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AntiCheckOutput implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AntiCheckOutput() {
    }




}